#!/bin/bash

export home="$HOME"
export conf="$home/projects/configuration"

ln -sf $conf/emacs                 $home/.emacs
ln -sf $conf/tmux.conf             $home/.tmux.conf
ln -sf $conf/vim/vimrc             $home/.vimrc
ln -sf $conf/vim/vim               $home/.vim

ln -sf $conf/bash/bashrc           $home/.bashrc
ln -sf $conf/bash/bash_profile     $home/.bash_profile

ln -sf $conf/bcrc                  $home/.bcrc
ln -sf $conf/git/gitconfig         $home/.gitconfig
ln -sf $conf/ssh-config            $home/.ssh/config

if [[ "$(uname)" == 'Linux'  ]]; then
  ln -sf $conf/bash/xinitrc        $home/.xinitrc
  ln -sf $conf/conky/conkyrc       $home/.conkyrc
  ln -sf $conf/openbox             $home/.config/openbox
  ln -sf $conf/x11/Xmodmap-linux   $home/.Xmodmap
fi

if [[ "$(uname)" == 'Darwin'  ]]; then
  ln -sf $conf/x11/Xmodmap-mac     $home/.Xmodmap
fi

rm $home/.vim/vim
rm $home/.config/openbox/openbox
