#!/bin/bash

docker run --detach \
           --interactive \
           --volume /:/mac \
           --publish 4000:4000 \
           --publish 8090:8090 \
           --add-host cherry:192.168.0.39 \
           --add-host rorschach:192.168.0.72 \
           --add-host adam:192.168.0.98 \
           --add-host xenorophidae:192.168.0.133 \
           --add-host reykjavik:10.35.0.3 \
           --env DISPLAY=192.168.0.21:0 \
           --hostname system \
           --privileged \
           --name system system
