# ~/.bash_profile

export home="$HOME/home"
export conf="$home/projects/configuration"

# Terminal colors
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

# Adjust the path
if [[ -d "$home/bin" ]]; then PATH="$PATH:$home/bin"; fi # Include user's private bin

# Aliases
alias conf="cd $conf"
alias dockrun="$conf/mac/docker/run"
alias sys="docker exec -it system su -l joyce"
alias u="cd .."
