#!/bin/bash

docker run --detach \
           --interactive \
           --volume /:/mac \
           --add-host cherry:192.168.0.39 \
           --add-host rorschach:192.168.0.72 \
           --add-host reykjavik:10.35.0.3 \
           --hostname system \
           --name system system
