# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Define two very important variables
export home="$HOME"
export conf="$home/projects/configuration"

# Source Spencer's dotbash
source "$home/.bash/init"

# Adjust the path
if [[ -d "$home/bin" ]]; then PATH="$PATH:$home/bin"; fi # Include user's private bin

# Source aliases and program-specific functions
if [[ -f "$conf/bash/includes/aliases"   ]];                                 then source "$conf/bash/includes/aliases"; fi
if [[ -f "$conf/bash/includes/common"    ]];                                 then source "$conf/bash/includes/common";  fi
if [[ -f "$conf/bash/includes/linux"     ]] && [[ "$(uname)" == 'Linux'  ]]; then source "$conf/bash/includes/linux";   fi
if [[ -f "$conf/bash/includes/mac"       ]] && [[ "$(uname)" == 'Darwin' ]]; then source "$conf/bash/includes/mac";     fi

# Terminal settings
eval $(dircolors $conf/bash/includes/dir_colors)  # Display broken symlinks. Needs to go after the Mac includes because it requires the gnu coreutils.
export EDITOR="/usr/bin/vim"
export VISUAL="/usr/bin/vim"
export LC_CTYPE='en_US.utf-8'
export DISPLAY=:0.0
if [[ "$TERM" != 'linux' ]]; then export TERM='xterm-256color'; fi # Check necessary for Linux's console mode vim.

# Bash history
HISTCONTROL=ignoredups:ignorespace    # Don't put duplicate lines in the history.
shopt -s histappend                   # Append to the history file, don't overwrite it
HISTSIZE=1000
HISTFILESIZE=2000
