#!/bin/bash
#if [[ "$(uname)" == 'Linux' ]];
  openbox &
  wm_pid=$!

  init_session() {
    xset r rate 150 30
    ~/.config/openbox/set-desktop-grid 0 10 10 0
    nitrogen --set-zoom-fill ~/.config/openbox/background.jpg
    xrdb ~/.Xresources
    lxsession &
    xcompmgr &

    gnome-terminal &
  }

  sleep 2 && init_session

  wait $wm_pid
#fi
